### PR TITLE
Event page redesign

### PR DESCRIPTION
**Pull request by rafaan**

### CODE REVIEW

**Comment by grayden** [comment]
@rafaan I was just reviewing this. When you're not logged in, the tooltip over the upvote button disappears out of the page. Otherwise, love the new look! :+1:

**Comment by rafaan** [comment]
Ah ok, thanks.  I was going to add some space between the navbar and event card anyway so that should fix it.

**Comment by rafaan** [comment]
@grayden ready for staging :)

**Comment by grayden** [comment]
@rafaan are you sure? I'll check it out :stuck_out_tongue:

**Comment by rafaan** [comment]
haha i hope so...

**Pull request merged**
