### PR TITLE
Fix for a few screen resolutions in the responsive math gap

### PR DESCRIPTION
**Pull request by mcongrove**
There are a few edge cases where users were seeing random element sizes and placements. These minor changes fix those.

### CODE REVIEW

**Comment by grayden** [comment]
@mcongrove this looks good, actually as it always should have been. Did we change these previously ourselves?

**Comment by grayden** [comment]
@mcongrove what pages did you encounter this issue on?

**Comment by mcongrove** [comment]
I encountered the issue on the home page.

**Comment by grayden** [comment]
@mcongrove cool, I think I see what you mean.

**Comment by grayden** [comment]
@mcongrove take a look at the the elements inside the navbar when it goes into dropdown mode, a few pieces in there need to be hidden sooner.

**Comment by netikular** [comment]
@Forekasting/contributors this is super old!! is it still relevant?

**Comment by grayden** [comment]
@mcongrove ^^ Kevin's question.

**Comment by grayden** [comment]
closing since Rafaan is overhauling the design of the site anyway.

**Pull request closed without merging**
